#!/bin/sh

MAX_DELAY=
MAX_LINES=

[ -r /etc/default/rsyslog-s3 ] && . /etc/default/rsyslog-s3

export S3_SYSLOG_ACCESS_KEY
export S3_SYSLOG_SECRET_KEY
export S3_SYSLOG_BUCKET

if [ "$S3_SYSLOG_KEY_FORMAT" ]
then export S3_SYSLOG_KEY_FORMAT
fi

ARGS=

if [ "$MAX_DELAY" ]
then ARGS="$ARGS --delay $MAX_DELAY"
fi

if [ "$MAX_LINES" ]
then ARGS="$ARGS --lines $MAX_LINES"
fi

exec ${PYTHON:-python} -u /usr/lib/rsyslog-s3-omprog.py $ARGS
